=== Lynthar/Mount-Blade-Mods/CaptivityEvents/CaptivityEventsV1.3.11.1311/Modules/zCaptivityEvents/ModuleLoader/CaptivityRequired/Events/CECustomScenes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!--  VERSION 1.0  -->
   <xs:element name="CECustomScenes">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="CEScene" />
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name="CEScene">
      <xs:complexType>
         <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
               <xs:element ref="Name" />
               <xs:element ref="Dialogue" minOccurs="0" />
            </xs:choice>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <!-- Name -->
   <xs:element name="Name" type="xs:string" />

   <xs:element name="Dialogue">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="Line" />
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name="Line">
      <xs:complexType>
         <xs:attribute name="Id" type="xs:string" />
         <xs:attribute name="Ref" type="xs:string" />
         <xs:attribute name="InputToken" type="xs:string" />
         <xs:attribute name="OutputToken" type="xs:string" />
         <xs:attribute name="Text" type="xs:string" />
         <xs:attribute name="NextScene" type="xs:string" />
         <xs:attribute name="Condition" type="xs:string" />
         <xs:attribute name="Consequence" type="xs:string" />
      </xs:complexType>
   </xs:element>

</xs:schema>

=== Lynthar/Mount-Blade-Mods/CaptivityEvents/CEDefaultEvents1311/Modules/zCEDefaults/Scenes/DefaultSlaveryScene.xml
<?xml version="1.0" encoding="UTF-8"?>
<CECustomScenes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://CECustomScenes.xsd">
   <CEScene>
      <Name>TheSlaveryScene</Name>
      <Dialogue>
         <Line Id="FirstLine" Ref="AI" InputToken="start" OutputToken="FirstResponse" Text="Wake up, whore! We are going for a nice walk.[ib:confident][rb:very_positive]" />

         <Line Id="FirstLineResponse1" Ref="Player" InputToken="FirstResponse" OutputToken="FirstResponse1" Text="Let me go, bastard!" />
         <Line Id="FirstLineResponse2" Ref="Player" InputToken="FirstResponse" OutputToken="FirstResponse2" Text="(Silence)" />
         <Line Id="FirstLineResponse3" Ref="Player" InputToken="FirstResponse" OutputToken="FirstResponse3" Text="I don't want to talk to you." />

         <Line Id="FirstResponse1AI" Ref="AI" InputToken="FirstResponse1" OutputToken="close_window" Text="Hahaha, next time keep the morale up.[ib:confident][rb:very_positive]" />
         <Line Id="FirstResponse2AI" Ref="AI" InputToken="FirstResponse2" OutputToken="close_window" Text="Your pretty ass will fetch a nice sum, maybe enough to pay our wages.[ib:confident][rb:very_positive]" />
         <Line Id="FirstResponse3AI" Ref="AI" InputToken="FirstResponse3" OutputToken="close_window" Text="Nor do I.[ib:hip][rb:very_positive]" />
      </Dialogue>
   </CEScene>
</CECustomScenes>
