=== Lynthar/Mount-Blade-Mods/CaptivityEvents/CaptivityEventsV1.3.11.1311/Modules/zCaptivityEvents/ModuleLoader/CaptivityRequired/Events/CECustomModal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--  VERSION 1.0  -->
    <xs:element name="CECustom">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="1">
                    <xs:element ref="CEModuleName" />
                    <xs:element ref="CEFlags" minOccurs="0" />
                    <xs:element ref="CESkills" minOccurs="0"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CEModuleName" type="xs:string" />

    <xs:element name="CEFlags">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CEFlag" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CEFlag">
        <xs:complexType>
            <xs:attribute name="Id" type="xs:string" />
            <xs:attribute name="Name" type="xs:string" />
            <xs:attribute name="HintText" type="xs:string" />
            <xs:attribute name="DefaultValue" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="CESkills">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CESkill" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CESkill">
        <xs:complexType>
            <xs:attribute name="Id" type="xs:string" />
            <xs:attribute name="Name" type="xs:string" />
            <xs:attribute name="MinLevel" type="xs:string" />
            <xs:attribute name="MaxLevel" type="xs:string" />
            <xs:attribute name="SetZeroOnEscape" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Lynthar/Mount-Blade-Mods/CaptivityEvents/TranslationFiles/Modules/zCEArenaFighterExpansion/Settings/CEModuleCustom.xml
<?xml version="1.0" encoding="UTF-8"?>
<CECustom xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file://CECustomModal.xsd">
    <CEModuleName>Arena Fighter Expansion</CEModuleName>
    <CESkills>
        <CESkill Id="ArenaFighter" Name="Arena Fighter" MinLevel="0" MaxLevel="1"
            SetZeroOnEscape="true" />
        <CESkill Id="ArenaSlave" Name="Arena Slave Fighter" MinLevel="0" MaxLevel="1"
            SetZeroOnEscape="true" />
        <CESkill Id="ArenaFightOne" Name="Arena Fight One" MinLevel="0" MaxLevel="1" />
        <CESkill Id="ArenaFightTwo" Name="Arena Fight One" MinLevel="0" MaxLevel="1" />
        <CESkill Id="ArenaBrawlFightOne" Name="Arena Fight Brawl Fight One" MinLevel="0"
            MaxLevel="1" />
        <CESkill Id="ArenaSwordFightOne" Name="Arena Fight Sword Fight One" MinLevel="0"
            MaxLevel="1" />
        <CESkill Id="ArenaSwordFightTwo" Name="Arena Fight Sword Fight One" MinLevel="0"
            MaxLevel="1" />
        <CESkill Id="DinnerOption" Name="DinnerOption" MinLevel="0" MaxLevel="3"
            SetZeroOnEscape="true" />
    </CESkills>
</CECustom>

=== Lynthar/Mount-Blade-Mods/CaptivityEvents/ExampleExpansion/Modules/zCEExampleExpansion/Settings/CEModuleCustom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    自定义模块设置文件
    用于定义自定义技能和标志
-->
<CECustom xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../CaptivityEventsV1.3.11.1311/Modules/zCaptivityEvents/ModuleLoader/CaptivityRequired/Events/CECustomModal.xsd">

    <!-- 模块名称 -->
    <CEModuleName>Example Expansion</CEModuleName>

    <!-- 自定义技能定义（可选）
         这些技能会被mod追踪，可以在事件中使用
    -->
    <CESkills>
        <!-- 示例：声望等级技能 -->
        <CESkill
            Id="ExampleReputation"
            Name="{=EXSKILL001}示例声望"
            MinLevel="0"
            MaxLevel="100"
            SetZeroOnEscape="false"/>

        <!-- 示例：临时状态（逃跑后重置） -->
        <CESkill
            Id="ExampleTempStatus"
            Name="{=EXSKILL002}临时状态"
            MinLevel="0"
            MaxLevel="10"
            SetZeroOnEscape="true"/>
    </CESkills>

    <!-- 自定义标志定义（可选）
         这些是布尔值标志，可以在事件条件中使用
    -->
    <CEFlags>
        <CEFlag
            Id="ExampleFlag1"
            Name="{=EXFLAG001}示例标志1"
            HintText="这是一个示例标志"
            DefaultValue="false"/>

        <CEFlag
            Id="ExampleFlag2"
            Name="{=EXFLAG002}示例标志2"
            HintText="另一个示例标志"
            DefaultValue="true"/>
    </CEFlags>

</CECustom>
